### ISSUE TITLE
Unused key parts of vectors

### ISSUE THREAD

**Issue by minibotan** [txtxj/Unity-Animation-Compression-Keyframe-Reducer#2]
Problem is that keyframes frequently has unused parameters.
For example, if animation only moves object by Y axis, there are still may be saved X and Z info, that triples size?
Can you make them to disappear?

or should i create my own fork and make pull request?

**Comment by txtxj** [comment]
Yes there may be such a problem, one solution is to implement your own float curve class, refer to these two files and customize an `IKeyframeBase<float>` class and an `AnimationCurveBase<float>` class.
If you look at unity's built-in types of animation curves, it does seem like float curves could be added as a new feature to the package.(When controlling a public float variable in a script, rather than adjusting a component of a Vector3)
However, from the projects I've worked on, generally only transform-related curves are imported from external programs and thus may need to be compressed. All other single-float curves are adjusted manually. For transform-related curves, Unity may actually prefer that users get the curves as Vector3 and Quaternion (even if they only have one component used), as evidenced by the way EditorCurve is stored. Additionally, if float curves are to be added to the package for easy access by others, there may be a need to provide `KeyframeReducer` with more varied functionality for fetching animated curves, which may require a major refactoring of the project. So I would recommend that you implement float curves in your own project!

[Assets/Plugins/Citrine/KeyframeReducer/Editor/AnimationCurve/Vector3AnimationCurve.cs](Assets/Plugins/Citrine/KeyframeReducer/Editor/AnimationCurve/Vector3AnimationCurve.cs)
[Assets/Plugins/Citrine/KeyframeReducer/Editor/Keyframe/Vector3Keyframe.cs](Assets/Plugins/Citrine/KeyframeReducer/Editor/Keyframe/Vector3Keyframe.cs)

**Comment by minibotan** [comment]
Thanks!
